sudo: false

language: node_js

node_js:
  - '10'

branches:
  only:
    - master
    - travis-ci

install:
  - for dir in compassion.*; do (cd $dir && npm install --no-package-lock --no-save); done
  - npm install --no-package-lock --no-save
  - npm install -g nyc

script:
  - nyc npm test
