sudo: false

language: node_js

node_js:
  - '6'
  - '8'
  - '10'

branches:
  only:
    - master
    - travis-ci

install:
  - pip install --user awscli
  - for dir in compassion.*; do (cd $dir && npm install --no-package-lock --no-save); done
  - npm install --no-package-lock --no-save
  - npm install -g istanbul coveralls
  - git checkout .

after_script:
  - '[[ "$TRAVIS_PULL_REQUEST" = "false" ]] && aws s3 sync ./coverage s3://bigeasy/addendum/$TRAVIS_JOB_NUMBER/coverage'
  - '[[ "$TRAVIS_PULL_REQUEST" = "false" ]] && aws s3 sync ./compassion.colleague/t/entries.json s3://bigeasy/addendum/$TRAVIS_JOB_NUMBER/entries.json'
