sudo: false

language: node_js

node_js:
  - '4'
  - '6'
  - '8'

branches:
  only:
    - step
    - master
    - travis-ci

install:
  - for dir in compassion.*; do (cd $dir && yarn install --no-lockfile); done
  - yarn install --no-lockfile
  - yarn global add istanbul coveralls
  - git checkout .
