sudo: false

language: node_js

node_js:
  - '4'
  - '5'
  - '6'

branches:
  only:
    - master
    - travis-ci

before_install:
  - for dir in prolific*; do (cd $dir && npm install); done
  - npm install
  - npm install istanbul coveralls
