sudo: false

language: node_js

node_js:
#  - '4'
#  - '6'
#  - '7'
  - '8'

branches:
  only:
    - master
    - travis-ci

install:
  - for dir in compassion.*; do (cd $dir && npm install); done
  - npm install istanbul coveralls
  - git checkout .
