#!/bin/sh

node_modules=$(cd $(dirname $0) && echo $PWD)/../node_modules

if ! [ -e "$node_modules/proof" ]; then
    echo "you must: npm install proof" 1>&2
    exit 1
fi

PATH="$PATH:$node_modules/.bin"

set -e

echo ""

(proof run */t/*.t.js | tee .proof.out | proof progress) \
  || (proof errors < .proof.out) \
  || exit 1

if [ "$CI" = "true" ]; then
  echo ""
  echo "running with coverage"
  t/cover
  node_modules/.bin/istanbul report --format text
fi

echo ""
